/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SlimRouteImport } from './routes/_slim'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SlimForgotPasswordRouteImport } from './routes/_slim/forgot-password'
import { Route as SlimLoginRouteImport } from './routes/_slim/login'
import { Route as SlimOrderRouteImport } from './routes/_slim/order'
import { Route as SlimRegisterRouteImport } from './routes/_slim/register'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardCommissionsRouteImport } from './routes/_authed/dashboard/commissions'
import { Route as AuthedDashboardCookingGasRouteImport } from './routes/_authed/dashboard/cooking-gas'
import { Route as AuthedDashboardDangoteDeliveryRouteImport } from './routes/_authed/dashboard/dangote-delivery'
import { Route as AuthedDashboardLicensesRouteImport } from './routes/_authed/dashboard/licenses'
import { Route as AuthedDashboardOrdersRouteImport } from './routes/_authed/dashboard/orders'
import { Route as AuthedDashboardPricesRouteImport } from './routes/_authed/dashboard/prices'
import { Route as AuthedDashboardProfileRouteImport } from './routes/_authed/dashboard/profile'
import { Route as AuthedDashboardSettingsRouteImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardWalletRouteImport } from './routes/_authed/dashboard/wallet'
import { Route as SiteTRefRouteImport } from './routes/_site/t.$ref'
import { Route as SlimOrderCookingGasRouteImport } from './routes/_slim/order_.cooking-gas'
import { Route as SlimOrderDangoteDeliveryRouteImport } from './routes/_slim/order_.dangote-delivery'
import { Route as SlimOrderDepotRouteImport } from './routes/_slim/order_.depot'
import { Route as SlimOrderNewRouteImport } from './routes/_slim/order_.new'
import { Route as AuthedDashboardCookingGasOrderIdRouteImport } from './routes/_authed/dashboard/cooking-gas_.$orderId'
import { Route as AuthedDashboardDangoteDeliveryOrderIdRouteImport } from './routes/_authed/dashboard/dangote-delivery_.$orderId'
import { Route as AuthedDashboardOrdersOrderIdRouteImport } from './routes/_authed/dashboard/orders_.$orderId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SlimRoute = SlimRouteImport.update({
  id: '/_slim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SlimForgotPasswordRoute = SlimForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => SlimRoute,
} as any)
const SlimLoginRoute = SlimLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SlimRoute,
} as any)
const SlimOrderRoute = SlimOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => SlimRoute,
} as any)
const SlimRegisterRoute = SlimRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SlimRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardCommissionsRoute =
  AuthedDashboardCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardCookingGasRoute =
  AuthedDashboardCookingGasRouteImport.update({
    id: '/cooking-gas',
    path: '/cooking-gas',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardDangoteDeliveryRoute =
  AuthedDashboardDangoteDeliveryRouteImport.update({
    id: '/dangote-delivery',
    path: '/dangote-delivery',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardLicensesRoute = AuthedDashboardLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardOrdersRoute = AuthedDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardPricesRoute = AuthedDashboardPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardProfileRoute = AuthedDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardSettingsRoute = AuthedDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardWalletRoute = AuthedDashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const SiteTRefRoute = SiteTRefRouteImport.update({
  id: '/t/$ref',
  path: '/t/$ref',
  getParentRoute: () => SiteRoute,
} as any)
const SlimOrderCookingGasRoute = SlimOrderCookingGasRouteImport.update({
  id: '/order_/cooking-gas',
  path: '/order/cooking-gas',
  getParentRoute: () => SlimRoute,
} as any)
const SlimOrderDangoteDeliveryRoute =
  SlimOrderDangoteDeliveryRouteImport.update({
    id: '/order_/dangote-delivery',
    path: '/order/dangote-delivery',
    getParentRoute: () => SlimRoute,
  } as any)
const SlimOrderDepotRoute = SlimOrderDepotRouteImport.update({
  id: '/order_/depot',
  path: '/order/depot',
  getParentRoute: () => SlimRoute,
} as any)
const SlimOrderNewRoute = SlimOrderNewRouteImport.update({
  id: '/order_/new',
  path: '/order/new',
  getParentRoute: () => SlimRoute,
} as any)
const AuthedDashboardCookingGasOrderIdRoute =
  AuthedDashboardCookingGasOrderIdRouteImport.update({
    id: '/cooking-gas_/$orderId',
    path: '/cooking-gas/$orderId',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardDangoteDeliveryOrderIdRoute =
  AuthedDashboardDangoteDeliveryOrderIdRouteImport.update({
    id: '/dangote-delivery_/$orderId',
    path: '/dangote-delivery/$orderId',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardOrdersOrderIdRoute =
  AuthedDashboardOrdersOrderIdRouteImport.update({
    id: '/orders_/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/forgot-password': typeof SlimForgotPasswordRoute
  '/login': typeof SlimLoginRoute
  '/order': typeof SlimOrderRoute
  '/register': typeof SlimRegisterRoute
  '/dashboard/commissions': typeof AuthedDashboardCommissionsRoute
  '/dashboard/cooking-gas': typeof AuthedDashboardCookingGasRoute
  '/dashboard/dangote-delivery': typeof AuthedDashboardDangoteDeliveryRoute
  '/dashboard/licenses': typeof AuthedDashboardLicensesRoute
  '/dashboard/orders': typeof AuthedDashboardOrdersRoute
  '/dashboard/prices': typeof AuthedDashboardPricesRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/t/$ref': typeof SiteTRefRoute
  '/order/cooking-gas': typeof SlimOrderCookingGasRoute
  '/order/dangote-delivery': typeof SlimOrderDangoteDeliveryRoute
  '/order/depot': typeof SlimOrderDepotRoute
  '/order/new': typeof SlimOrderNewRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/cooking-gas/$orderId': typeof AuthedDashboardCookingGasOrderIdRoute
  '/dashboard/dangote-delivery/$orderId': typeof AuthedDashboardDangoteDeliveryOrderIdRoute
  '/dashboard/orders/$orderId': typeof AuthedDashboardOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/forgot-password': typeof SlimForgotPasswordRoute
  '/login': typeof SlimLoginRoute
  '/order': typeof SlimOrderRoute
  '/register': typeof SlimRegisterRoute
  '/dashboard/commissions': typeof AuthedDashboardCommissionsRoute
  '/dashboard/cooking-gas': typeof AuthedDashboardCookingGasRoute
  '/dashboard/dangote-delivery': typeof AuthedDashboardDangoteDeliveryRoute
  '/dashboard/licenses': typeof AuthedDashboardLicensesRoute
  '/dashboard/orders': typeof AuthedDashboardOrdersRoute
  '/dashboard/prices': typeof AuthedDashboardPricesRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/t/$ref': typeof SiteTRefRoute
  '/order/cooking-gas': typeof SlimOrderCookingGasRoute
  '/order/dangote-delivery': typeof SlimOrderDangoteDeliveryRoute
  '/order/depot': typeof SlimOrderDepotRoute
  '/order/new': typeof SlimOrderNewRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/cooking-gas/$orderId': typeof AuthedDashboardCookingGasOrderIdRoute
  '/dashboard/dangote-delivery/$orderId': typeof AuthedDashboardDangoteDeliveryOrderIdRoute
  '/dashboard/orders/$orderId': typeof AuthedDashboardOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_slim': typeof SlimRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_slim/forgot-password': typeof SlimForgotPasswordRoute
  '/_slim/login': typeof SlimLoginRoute
  '/_slim/order': typeof SlimOrderRoute
  '/_slim/register': typeof SlimRegisterRoute
  '/_site/': typeof SiteIndexRoute
  '/_authed/dashboard/commissions': typeof AuthedDashboardCommissionsRoute
  '/_authed/dashboard/cooking-gas': typeof AuthedDashboardCookingGasRoute
  '/_authed/dashboard/dangote-delivery': typeof AuthedDashboardDangoteDeliveryRoute
  '/_authed/dashboard/licenses': typeof AuthedDashboardLicensesRoute
  '/_authed/dashboard/orders': typeof AuthedDashboardOrdersRoute
  '/_authed/dashboard/prices': typeof AuthedDashboardPricesRoute
  '/_authed/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed/dashboard/wallet': typeof AuthedDashboardWalletRoute
  '/_site/t/$ref': typeof SiteTRefRoute
  '/_slim/order_/cooking-gas': typeof SlimOrderCookingGasRoute
  '/_slim/order_/dangote-delivery': typeof SlimOrderDangoteDeliveryRoute
  '/_slim/order_/depot': typeof SlimOrderDepotRoute
  '/_slim/order_/new': typeof SlimOrderNewRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/cooking-gas_/$orderId': typeof AuthedDashboardCookingGasOrderIdRoute
  '/_authed/dashboard/dangote-delivery_/$orderId': typeof AuthedDashboardDangoteDeliveryOrderIdRoute
  '/_authed/dashboard/orders_/$orderId': typeof AuthedDashboardOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/order'
    | '/register'
    | '/dashboard/commissions'
    | '/dashboard/cooking-gas'
    | '/dashboard/dangote-delivery'
    | '/dashboard/licenses'
    | '/dashboard/orders'
    | '/dashboard/prices'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/t/$ref'
    | '/order/cooking-gas'
    | '/order/dangote-delivery'
    | '/order/depot'
    | '/order/new'
    | '/dashboard/'
    | '/dashboard/cooking-gas/$orderId'
    | '/dashboard/dangote-delivery/$orderId'
    | '/dashboard/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/order'
    | '/register'
    | '/dashboard/commissions'
    | '/dashboard/cooking-gas'
    | '/dashboard/dangote-delivery'
    | '/dashboard/licenses'
    | '/dashboard/orders'
    | '/dashboard/prices'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/t/$ref'
    | '/order/cooking-gas'
    | '/order/dangote-delivery'
    | '/order/depot'
    | '/order/new'
    | '/dashboard'
    | '/dashboard/cooking-gas/$orderId'
    | '/dashboard/dangote-delivery/$orderId'
    | '/dashboard/orders/$orderId'
  id:
    | '__root__'
    | '/_authed'
    | '/_site'
    | '/_slim'
    | '/_authed/dashboard'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/privacy'
    | '/_site/terms'
    | '/_slim/forgot-password'
    | '/_slim/login'
    | '/_slim/order'
    | '/_slim/register'
    | '/_site/'
    | '/_authed/dashboard/commissions'
    | '/_authed/dashboard/cooking-gas'
    | '/_authed/dashboard/dangote-delivery'
    | '/_authed/dashboard/licenses'
    | '/_authed/dashboard/orders'
    | '/_authed/dashboard/prices'
    | '/_authed/dashboard/profile'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/wallet'
    | '/_site/t/$ref'
    | '/_slim/order_/cooking-gas'
    | '/_slim/order_/dangote-delivery'
    | '/_slim/order_/depot'
    | '/_slim/order_/new'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/cooking-gas_/$orderId'
    | '/_authed/dashboard/dangote-delivery_/$orderId'
    | '/_authed/dashboard/orders_/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  SlimRoute: typeof SlimRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_slim': {
      id: '/_slim'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SlimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_slim/forgot-password': {
      id: '/_slim/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof SlimForgotPasswordRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_slim/login': {
      id: '/_slim/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SlimLoginRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_slim/order': {
      id: '/_slim/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof SlimOrderRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_slim/register': {
      id: '/_slim/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof SlimRegisterRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/commissions': {
      id: '/_authed/dashboard/commissions'
      path: '/commissions'
      fullPath: '/dashboard/commissions'
      preLoaderRoute: typeof AuthedDashboardCommissionsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/cooking-gas': {
      id: '/_authed/dashboard/cooking-gas'
      path: '/cooking-gas'
      fullPath: '/dashboard/cooking-gas'
      preLoaderRoute: typeof AuthedDashboardCookingGasRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/dangote-delivery': {
      id: '/_authed/dashboard/dangote-delivery'
      path: '/dangote-delivery'
      fullPath: '/dashboard/dangote-delivery'
      preLoaderRoute: typeof AuthedDashboardDangoteDeliveryRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/licenses': {
      id: '/_authed/dashboard/licenses'
      path: '/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof AuthedDashboardLicensesRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/orders': {
      id: '/_authed/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthedDashboardOrdersRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/prices': {
      id: '/_authed/dashboard/prices'
      path: '/prices'
      fullPath: '/dashboard/prices'
      preLoaderRoute: typeof AuthedDashboardPricesRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/profile': {
      id: '/_authed/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthedDashboardProfileRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/wallet': {
      id: '/_authed/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthedDashboardWalletRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_site/t/$ref': {
      id: '/_site/t/$ref'
      path: '/t/$ref'
      fullPath: '/t/$ref'
      preLoaderRoute: typeof SiteTRefRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_slim/order_/cooking-gas': {
      id: '/_slim/order_/cooking-gas'
      path: '/order/cooking-gas'
      fullPath: '/order/cooking-gas'
      preLoaderRoute: typeof SlimOrderCookingGasRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_slim/order_/dangote-delivery': {
      id: '/_slim/order_/dangote-delivery'
      path: '/order/dangote-delivery'
      fullPath: '/order/dangote-delivery'
      preLoaderRoute: typeof SlimOrderDangoteDeliveryRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_slim/order_/depot': {
      id: '/_slim/order_/depot'
      path: '/order/depot'
      fullPath: '/order/depot'
      preLoaderRoute: typeof SlimOrderDepotRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_slim/order_/new': {
      id: '/_slim/order_/new'
      path: '/order/new'
      fullPath: '/order/new'
      preLoaderRoute: typeof SlimOrderNewRouteImport
      parentRoute: typeof SlimRoute
    }
    '/_authed/dashboard/cooking-gas_/$orderId': {
      id: '/_authed/dashboard/cooking-gas_/$orderId'
      path: '/cooking-gas/$orderId'
      fullPath: '/dashboard/cooking-gas/$orderId'
      preLoaderRoute: typeof AuthedDashboardCookingGasOrderIdRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/dangote-delivery_/$orderId': {
      id: '/_authed/dashboard/dangote-delivery_/$orderId'
      path: '/dangote-delivery/$orderId'
      fullPath: '/dashboard/dangote-delivery/$orderId'
      preLoaderRoute: typeof AuthedDashboardDangoteDeliveryOrderIdRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/orders_/$orderId': {
      id: '/_authed/dashboard/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof AuthedDashboardOrdersOrderIdRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
  }
}

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardCommissionsRoute: typeof AuthedDashboardCommissionsRoute
  AuthedDashboardCookingGasRoute: typeof AuthedDashboardCookingGasRoute
  AuthedDashboardDangoteDeliveryRoute: typeof AuthedDashboardDangoteDeliveryRoute
  AuthedDashboardLicensesRoute: typeof AuthedDashboardLicensesRoute
  AuthedDashboardOrdersRoute: typeof AuthedDashboardOrdersRoute
  AuthedDashboardPricesRoute: typeof AuthedDashboardPricesRoute
  AuthedDashboardProfileRoute: typeof AuthedDashboardProfileRoute
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardWalletRoute: typeof AuthedDashboardWalletRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardCookingGasOrderIdRoute: typeof AuthedDashboardCookingGasOrderIdRoute
  AuthedDashboardDangoteDeliveryOrderIdRoute: typeof AuthedDashboardDangoteDeliveryOrderIdRoute
  AuthedDashboardOrdersOrderIdRoute: typeof AuthedDashboardOrdersOrderIdRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardCommissionsRoute: AuthedDashboardCommissionsRoute,
  AuthedDashboardCookingGasRoute: AuthedDashboardCookingGasRoute,
  AuthedDashboardDangoteDeliveryRoute: AuthedDashboardDangoteDeliveryRoute,
  AuthedDashboardLicensesRoute: AuthedDashboardLicensesRoute,
  AuthedDashboardOrdersRoute: AuthedDashboardOrdersRoute,
  AuthedDashboardPricesRoute: AuthedDashboardPricesRoute,
  AuthedDashboardProfileRoute: AuthedDashboardProfileRoute,
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardWalletRoute: AuthedDashboardWalletRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardCookingGasOrderIdRoute: AuthedDashboardCookingGasOrderIdRoute,
  AuthedDashboardDangoteDeliveryOrderIdRoute:
    AuthedDashboardDangoteDeliveryOrderIdRoute,
  AuthedDashboardOrdersOrderIdRoute: AuthedDashboardOrdersOrderIdRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteTRefRoute: typeof SiteTRefRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteTRefRoute: SiteTRefRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface SlimRouteChildren {
  SlimForgotPasswordRoute: typeof SlimForgotPasswordRoute
  SlimLoginRoute: typeof SlimLoginRoute
  SlimOrderRoute: typeof SlimOrderRoute
  SlimRegisterRoute: typeof SlimRegisterRoute
  SlimOrderCookingGasRoute: typeof SlimOrderCookingGasRoute
  SlimOrderDangoteDeliveryRoute: typeof SlimOrderDangoteDeliveryRoute
  SlimOrderDepotRoute: typeof SlimOrderDepotRoute
  SlimOrderNewRoute: typeof SlimOrderNewRoute
}

const SlimRouteChildren: SlimRouteChildren = {
  SlimForgotPasswordRoute: SlimForgotPasswordRoute,
  SlimLoginRoute: SlimLoginRoute,
  SlimOrderRoute: SlimOrderRoute,
  SlimRegisterRoute: SlimRegisterRoute,
  SlimOrderCookingGasRoute: SlimOrderCookingGasRoute,
  SlimOrderDangoteDeliveryRoute: SlimOrderDangoteDeliveryRoute,
  SlimOrderDepotRoute: SlimOrderDepotRoute,
  SlimOrderNewRoute: SlimOrderNewRoute,
}

const SlimRouteWithChildren = SlimRoute._addFileChildren(SlimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  SlimRoute: SlimRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
